<html>
<head>
	<title>РГТЭУ Кемеровский институт</title>
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <META name="Иванов Даниил ПИ-172"content="http://alius.ru"></META>
    <meta name="Copyright" content="http://alius.ru">
    
    </head>
    
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" rightmargin="0" bottommargin="0" bgcolor="#D3D3D3">
<link href="index.css"type="text/css" rel="STYLESHEET">

<table border=1 width=100% height=20%>

<td width=100% height=20% align=center> Лабораторные работы по курсу "Разработка интернет приложений в сфере коммерции посредством PHP и MySQL" <br> Студента группы ПИ-172: Ивановым Даниилом Сергеевичом <br> Проверил: к.т.н. доц. Назимов А.С.
</td>
</table>

 <table border=1 width=100% >
     <td width=30%  align=left valign=top>
         <a href="../../orderform.php"> Первая лабораторная работа </a>
         <br><br>
         <a href="orderform_2.php"> Вторая лабораторная работа </a>
         <br><br>
         <a href="orderform_3.php"> Третья лабораторная работа</a>
         <br><br>
	<a href="orderform_4.php"> Четвертая лабораторная работа</a>
	<br><br>
	<a href="index_5.php"> Пятая лабораторная работа</a>
	<br><br>
	<a href="index_6.php"> Шестая лабораторная работа</a>
	<br><br>
         <a href="autoforum_galery.php"> Фотогалерея на PHP</a>
         <br><br>
         <a href="galery_java.php"> Фотогалерея на JavaScript</a>
     </td>
     <td width=70%  align=center>